name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --optimize-autoloader --no-dev
      - name: Build assets
        run: npm ci && npm run production
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          password: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}
          script: |
            cd /var/www/html/laravel
            git pull origin master
            composer install --optimize-autoloader --no-dev --no-scripts
            php artisan migrate --force
            chown -R www-data:www-data .
            chmod -R 775 storage bootstrap/cache
            sudo systemctl restart php7.4-fpm
